# //
# // Felipe Bedinotto Fava - 1801560675
# // Ueslei Bervanger Brandt - 
# //

CC = g++
CFLAGS = -Wall -g

executable:
	$(CC) $(CFLAGS) -o executable main.cpp decompress.cpp compress.cpp

clean:
	rm executable
